/**
 * Write a function that will produce the n-th number within the fibonacci sequence.
 * The fibonacci sequence is the series of numbers:
 * 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233
 * The next number is generated by adding up the previous two number before it.
 * Therefore the n-th number = fib(n-1) + fib(n-2)
 * Example
 * fib(1) = 1
 * fib(2) = 1
 * fib(3) = 2
 * fib(4) = 3
 * ...
 */

function fib(n) {

}

module.exports = {
    fib
};